version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - mongodb
      - qdrant
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - .:/app